In [3]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_validate

defenders = pd.read_csv(r'C:\Users\sosan\Documents\Dissertation\DataSets\Fifa 20\TransformedData\Defenders.csv')

In [73]:
defenders.loc[2768, 'BP']

0

In [5]:
defenders.loc[defenders['BP'] != 'CB', 'BP'] = 1
defenders.loc[defenders['BP'] == 'CB', 'BP'] = 0
defenders['BP'].head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    1
8    0
9    0
Name: BP, dtype: object

In [6]:
indexes = defenders._get_numeric_data().columns
print(indexes)

Index(['Age', 'Overall', 'Potential', 'ID', 'Height', 'Weight', 'BOV',
       'Growth', 'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill',
       'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control',
       'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions',
       'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength',
       'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning',
       'Vision', 'Penalties', 'Composure', 'Defending', 'Marking',
       'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving',
       'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes',
       'Total Stats', 'Base Stats', 'W/F', 'SM', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY'],
      dtype='object')


In [8]:
defenders = defenders[(defenders['BP'] != 'CB')]



numerical_Data = defenders[['Age', 'Overall', 'Potential', 'Height', 'Weight', 'BOV',
       'Growth', 'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill',
       'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control',
       'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions',
       'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength',
       'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning',
       'Vision', 'Penalties', 'Composure', 'Defending', 'Marking',
       'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving',
       'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes',
       'Total Stats', 'Base Stats', 'W/F', 'SM', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY']]

min_max = MinMaxScaler()
player = min_max.fit_transform(numerical_Data)
df_scaled = pd.DataFrame(player, columns=numerical_Data.columns,index=numerical_Data.index)
df_scaled.head(5)

Age   Overall  Potential    Height    Weight       BOV  Growth     Value  \
0  0.44  1.000000   1.000000  0.776805  0.822957  1.000000    0.04  0.079055   
1  0.48  0.976744   0.976744  0.667396  0.760700  0.976744    0.08  0.068275   
2  0.68  0.976744   0.976744  0.555799  0.628405  1.000000    0.00  0.031314   
3  0.72  0.976744   0.976744  0.667396  0.680934  0.976744    0.00  0.024127   
4  0.68  0.953488   0.953488  0.667396  0.548638  0.976744    0.00  0.027721   

       Wage  Release Clause  ...  Base Stats  W/F   SM        IR       PAC  \
0  0.665552        0.149649  ...    0.911765  0.5  0.0  0.666667  0.746479   
1  0.498328        0.119157  ...    0.698529  0.5  0.0  0.666667  0.661972   
2  1.000000        0.063791  ...    0.933824  0.5  0.5  1.000000  0.676056   
3  0.715719        0.039519  ...    0.727941  0.5  0.0  1.000000  0.619718   
4  0.448161        0.046740  ...    0.731618  0.5  0.0  0.666667  0.507042   

        SHO       PAS       DRI       DEF       PHY  
0  0.725806  0.766667  0.786885  1.000000  0.938776  
1  0.209677  0.500000  0.721311  0.979592  0.959184  
2  0.854839  0.850000  0.819672  0.938776  0.918367  
3  0.500000  0.566667  0.606557  1.000000  0.857143  
4  0.532258  0.666667  0.622951  0.979592  0.877551  

[5 rows x 62 columns]

In [9]:
DataFrame_Correlation_matrix = df_scaled.corr()
print(DataFrame_Correlation_matrix['Overall'].sort_values(ascending=False))

Overall           1.000000
Potential         1.000000
BOV               0.992123
DEF               0.951440
Defending         0.943572
                    ...   
GK Reflexes       0.046789
Balance          -0.029860
Value            -0.230731
Release Clause   -0.404690
Growth           -0.521768
Name: Overall, Length: 62, dtype: float64


In [50]:
predictorFeatures = indexes.drop(['Overall','ID'])
x_variable, y_variable = df_scaled[predictorFeatures], defenders.BP
x_variable.iloc[0:6]


Age  Potential    Height    Weight       BOV  Growth     Value      Wage  \
0  0.44   1.000000  0.776805  0.822957  1.000000    0.04  0.079055  0.665552   
1  0.48   0.976744  0.667396  0.760700  0.976744    0.08  0.068275  0.498328   
2  0.68   0.976744  0.555799  0.628405  1.000000    0.00  0.031314  1.000000   
3  0.72   0.976744  0.667396  0.680934  0.976744    0.00  0.024127  0.715719   
4  0.68   0.953488  0.667396  0.548638  0.976744    0.00  0.027721  0.448161   
5  0.64   0.953488  0.776805  0.680934  0.953488    0.00  0.037988  0.949833   

   Release Clause  Attacking  ...  Base Stats  W/F   SM        IR       PAC  \
0        0.149649   0.704981  ...    0.911765  0.5  0.0  0.666667  0.746479   
1        0.119157   0.344828  ...    0.698529  0.5  0.0  0.666667  0.661972   
2        0.063791   0.919540  ...    0.933824  0.5  0.5  1.000000  0.676056   
3        0.039519   0.574713  ...    0.727941  0.5  0.0  1.000000  0.619718   
4        0.046740   0.681992  ...    0.731618  0.5  0.0  0.666667  0.507042   
5        0.077131   0.831418  ...    0.805147  0.5  0.0  1.000000  0.450704   

        SHO       PAS       DRI       DEF       PHY  
0  0.725806  0.766667  0.786885  1.000000  0.938776  
1  0.209677  0.500000  0.721311  0.979592  0.959184  
2  0.854839  0.850000  0.819672  0.938776  0.918367  
3  0.500000  0.566667  0.606557  1.000000  0.857143  
4  0.532258  0.666667  0.622951  0.979592  0.877551  
5  0.741935  0.800000  0.737705  0.959184  0.816327  

[6 rows x 61 columns]

In [11]:
x_variable.iloc[:10]

Age  Potential    Height    Weight       BOV  Growth     Value      Wage  \
0  0.44   1.000000  0.776805  0.822957  1.000000    0.04  0.079055  0.665552   
1  0.48   0.976744  0.667396  0.760700  0.976744    0.08  0.068275  0.498328   
2  0.68   0.976744  0.555799  0.628405  1.000000    0.00  0.031314  1.000000   
3  0.72   0.976744  0.667396  0.680934  0.976744    0.00  0.024127  0.715719   
4  0.68   0.953488  0.667396  0.548638  0.976744    0.00  0.027721  0.448161   
5  0.64   0.953488  0.776805  0.680934  0.953488    0.00  0.037988  0.949833   
6  0.36   0.930233  0.667396  0.680934  0.930233    0.12  0.056982  0.648829   
7  0.56   0.930233  0.277899  0.354086  0.930233    0.00  0.040041  0.799331   
8  0.56   0.930233  0.610503  0.610895  0.930233    0.00  0.041068  0.515050   
9  0.56   0.930233  0.722101  0.857977  0.930233    0.00  0.041068  0.431438   

   Release Clause  Attacking  ...  Base Stats  W/F   SM        IR       PAC  \
0        0.149649   0.704981  ...    0.911765  0.5  0.0  0.666667  0.746479   
1        0.119157   0.344828  ...    0.698529  0.5  0.0  0.666667  0.661972   
2        0.063791   0.919540  ...    0.933824  0.5  0.5  1.000000  0.676056   
3        0.039519   0.574713  ...    0.727941  0.5  0.0  1.000000  0.619718   
4        0.046740   0.681992  ...    0.731618  0.5  0.0  0.666667  0.507042   
5        0.077131   0.831418  ...    0.805147  0.5  0.0  1.000000  0.450704   
6        0.108124   0.689655  ...    0.797794  0.5  0.0  0.333333  0.563380   
7        0.081244   0.934866  ...    0.988971  0.5  0.5  0.666667  0.929577   
8        0.075125   0.681992  ...    0.801471  0.5  0.0  0.666667  0.563380   
9        0.066901   0.831418  ...    0.794118  0.5  0.5  1.000000  0.380282   

        SHO       PAS       DRI       DEF       PHY  
0  0.725806  0.766667  0.786885  1.000000  0.938776  
1  0.209677  0.500000  0.721311  0.979592  0.959184  
2  0.854839  0.850000  0.819672  0.938776  0.918367  
3  0.500000  0.566667  0.606557  1.000000  0.857143  
4  0.532258  0.666667  0.622951  0.979592  0.877551  
5  0.741935  0.800000  0.737705  0.959184  0.816327  
6  0.564516  0.783333  0.737705  0.959184  0.857143  
7  0.870968  0.950000  0.983607  0.775510  0.673469  
8  0.645161  0.800000  0.704918  0.959184  0.795918  
9  0.693548  0.866667  0.803279  0.979592  0.734694  

[10 rows x 61 columns]

In [12]:
y_variable = y_variable.astype(int)
y_variable

0       0
1       0
2       0
3       0
4       0
       ..
6149    0
6150    0
6151    1
6152    1
6153    0
Name: BP, Length: 6154, dtype: int32

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_variable, y_variable, test_size=0.2)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(4923, 61) (4923,)
(1231, 61) (1231,)


In [32]:
X_train

Age  Potential    Height    Weight       BOV  Growth     Value  \
2041  0.36   0.511628  0.667396  0.645914  0.511628    0.16  0.000205   
5449  0.16   0.255814  0.498906  0.433852  0.255814    0.32  0.173511   
343   0.32   0.697674  0.610503  0.628405  0.744186    0.16  0.009240   
1077  0.48   0.581395  0.389497  0.468872  0.604651    0.00  0.001745   
295   0.52   0.697674  0.667396  0.725681  0.720930    0.00  0.006674   
...    ...        ...       ...       ...       ...     ...       ...   
5191  0.24   0.302326  0.332604  0.319066  0.302326    0.32  0.276181   
2512  0.16   0.488372  0.722101  0.822957  0.511628    0.32  0.000205   
267   0.60   0.720930  0.389497  0.486381  0.744186    0.00  0.006674   
4936  0.52   0.325581  0.389497  0.486381  0.348837    0.00  0.214579   
4193  0.48   0.372093  0.389497  0.371595  0.395349    0.00  0.332649   

          Wage  Release Clause  Attacking  ...  Base Stats   W/F   SM  \
2041  0.013378        0.001304   0.352490  ...    0.382353  0.25  0.0   
5449  0.000000        0.340020   0.252874  ...    0.375000  0.25  0.0   
343   0.070234        0.016851   0.712644  ...    0.757353  0.50  0.5   
1077  0.020067        0.002508   0.567050  ...    0.720588  1.00  0.5   
295   0.086957        0.011836   0.494253  ...    0.647059  0.50  0.0   
...        ...             ...        ...  ...         ...   ...  ...   
5191  0.000000        0.459378   0.367816  ...    0.481618  0.50  0.0   
2512  0.003344        0.001204   0.329502  ...    0.422794  0.25  0.0   
267   0.093645        0.012538   0.850575  ...    0.882353  0.50  1.0   
4936  0.003344        0.283852   0.306513  ...    0.389706  0.50  0.0   
4193  0.006689        0.504514   0.356322  ...    0.551471  0.25  0.0   

            IR       PAC       SHO       PAS       DRI       DEF       PHY  
2041  0.000000  0.295775  0.225806  0.383333  0.377049  0.551020  0.714286  
5449  0.000000  0.619718  0.177419  0.366667  0.491803  0.326531  0.367347  
343   0.333333  0.605634  0.564516  0.733333  0.770492  0.734694  0.816327  
1077  0.333333  0.718310  0.548387  0.716667  0.786885  0.591837  0.612245  
295   0.333333  0.408451  0.548387  0.700000  0.573770  0.775510  0.755102  
...        ...       ...       ...       ...       ...       ...       ...  
5191  0.000000  0.746479  0.322581  0.466667  0.606557  0.285714  0.367347  
2512  0.000000  0.478873  0.354839  0.350000  0.295082  0.551020  0.653061  
267   0.000000  0.788732  0.903226  0.783333  0.868852  0.673469  0.693878  
4936  0.000000  0.549296  0.193548  0.366667  0.573770  0.387755  0.367347  
4193  0.000000  0.746479  0.451613  0.500000  0.672131  0.346939  0.408163  

[4923 rows x 61 columns]

In [16]:
from sklearn.ensemble import RandomForestClassifier
RF_Model = RandomForestClassifier(max_features = 'sqrt', max_leaf_nodes = 5)
RF_Model.fit(X_train, y_train)

RandomForestClassifier(max_features='sqrt', max_leaf_nodes=5)

In [24]:
from sklearn.metrics import *

#Learning curve
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import f1_score
from sklearn.model_selection import learning_curve
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import validation_curve

# Import Classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

import numpy as np

y_train_pred  = RF_Model.predict(X_train)

Accuracy = round(np.median(cross_val_score(RF_Model, X_train, y_train, cv = 5)),2)*100
 
Error   = 1 - Accuracy
    
precision = precision_score(y_train, y_pred) * 100
recall = recall_score(y_train, y_pred) * 100
f1score = f1_score(y_train, y_pred) * 100

In [26]:
print('Scoring Accuracy: %.2f %%'%(Accuracy))
print("Precision: %.2f %%"%(precision))
print("Recall: %.2f %%"%(recall))
print('f1-score: %.2f %%'%(f1score))

print(y_train_pred)

Scoring Accuracy: 91.00 %
Precision: 88.64 %
Recall: 87.27 %
f1-score: 87.95 %
[0 0 0 ... 1 1 1]


In [27]:
print(confusion_matrix(y_train, y_pred))

[[2835  210]
 [ 239 1639]]


In [30]:
y_test_pred  = RF_Model.predict(X_test)
print(confusion_matrix(y_test, y_test_pred))

Accuracy = round(np.median(cross_val_score(RF_Model, X_test, y_test, cv = 5)),2)*100
 
Error   = 1 - Accuracy
    
precision = precision_score(y_test, y_test_pred) * 100
recall = recall_score(y_test, y_test_pred) * 100
f1score = f1_score(y_test, y_test_pred) * 100

print('Scoring Accuracy: %.2f %%'%(Accuracy))
print("Precision: %.2f %%"%(precision))
print("Recall: %.2f %%"%(recall))
print('f1-score: %.2f %%'%(f1score))

[[707  57]
 [ 77 390]]
Scoring Accuracy: 92.00 %
Precision: 87.25 %
Recall: 83.51 %
f1-score: 85.34 %


In [37]:
X_test

Age  Potential    Height    Weight       BOV  Growth     Value  \
4890  0.44   0.325581  0.610503  0.645914  0.372093    0.04  0.255647   
1190  0.64   0.581395  0.389497  0.354086  0.581395    0.00  0.000924   
3294  0.20   0.441860  0.498906  0.486381  0.465116    0.28  0.845996   
2768  0.68   0.465116  0.667396  0.628405  0.488372    0.00  0.358316   
1104  0.56   0.581395  0.610503  0.583658  0.604651    0.00  0.001540   
...    ...        ...       ...       ...       ...     ...       ...   
3309  0.28   0.441860  0.667396  0.548638  0.465116    0.24  0.820329   
349   0.64   0.697674  0.610503  0.628405  0.744186    0.00  0.005133   
2062  0.68   0.511628  0.610503  0.628405  0.534884    0.00  0.512320   
1688  0.36   0.534884  0.776805  0.583658  0.558140    0.20  0.001129   
761   0.44   0.627907  0.610503  0.566148  0.651163    0.00  0.004107   

          Wage  Release Clause  Attacking  ...  Base Stats   W/F   SM  \
4890  0.000000        0.556670   0.444444  ...    0.500000  0.50  0.0   
1190  0.023411        0.001505   0.624521  ...    0.702206  0.50  0.5   
3294  0.006689        0.000201   0.536398  ...    0.606618  0.50  0.0   
2768  0.003344        0.473420   0.417625  ...    0.500000  0.50  0.0   
1104  0.036789        0.004012   0.666667  ...    0.694853  0.50  0.5   
...        ...             ...        ...  ...         ...   ...  ...   
3309  0.003344        0.000301   0.501916  ...    0.533088  0.50  0.0   
349   0.070234        0.011635   0.758621  ...    0.724265  0.50  0.5   
2062  0.013378        0.801404   0.616858  ...    0.459559  0.50  0.0   
1688  0.013378        0.002508   0.310345  ...    0.404412  0.50  0.0   
761   0.063545        0.009027   0.747126  ...    0.738971  0.25  0.0   

            IR       PAC       SHO       PAS       DRI       DEF       PHY  
4890  0.000000  0.690141  0.338710  0.450000  0.590164  0.408163  0.448980  
1190  0.000000  0.704225  0.500000  0.683333  0.721311  0.571429  0.734694  
3294  0.000000  0.732394  0.419355  0.566667  0.672131  0.448980  0.591837  
2768  0.000000  0.352113  0.435484  0.516667  0.491803  0.448980  0.816327  
1104  0.000000  0.591549  0.612903  0.683333  0.704918  0.612245  0.693878  
...        ...       ...       ...       ...       ...       ...       ...  
3309  0.000000  0.577465  0.403226  0.633333  0.459016  0.510204  0.551020  
349   0.333333  0.366197  0.741935  0.716667  0.721311  0.714286  0.857143  
2062  0.000000  0.098592  0.516129  0.516667  0.508197  0.530612  0.755102  
1688  0.000000  0.323944  0.258065  0.416667  0.327869  0.591837  0.734694  
761   0.000000  0.492958  0.822581  0.716667  0.737705  0.693878  0.653061  

[1231 rows x 61 columns]

In [69]:
y_test_pred[0:10]

array([1, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [79]:
from sklearn.decomposition import PCA

pca = PCA()
pcad_data = pca.fit_transform(x_variable)
#percentage variation on each principal component
per_var = np.round(pca.explained_variance_ratio_ * 100, decimals=1)

#create lables for eachb principal component
labels = ['PC' + str(pc) for pc in range(1, len(per_var)+1)]

array([[ 1.99813451e+00,  9.96501712e-01, -2.59608551e-02, ...,
        -4.44193878e-16,  9.41531541e-16, -1.30903903e-16],
       [ 7.63429497e-01,  1.29817745e+00, -4.76778007e-01, ...,
        -5.68177129e-16,  1.40683862e-15, -1.00611135e-15],
       [ 2.56714229e+00,  7.35417226e-01,  5.26705517e-04, ...,
         3.91971819e-17, -3.81654174e-16, -3.57678678e-17],
       ...,
       [-1.59042825e+00, -6.80938774e-01, -5.12353199e-01, ...,
         2.58094458e-18, -1.90634778e-17,  1.10756768e-17],
       [-1.65119704e+00, -9.81640925e-01, -5.69461984e-01, ...,
        -2.70022360e-17,  6.96829203e-17,  1.01543591e-17],
       [-1.80071233e+00, -7.38893392e-01, -5.87198387e-01, ...,
        -5.13065781e-17,  4.33694690e-17, -6.86005704e-18]])